---
title: "Extracting BUSCO Loci"
author: "Jeremias Ivan"
date: "`r format(Sys.time(), '%d %B %Y, %H:%M%p')`"

output:
  html_document:
    code_folding: show
    toc: true
    toc_float: true

params:
  # --- General -------------------------------------------------
  codedir: "/home/user/PhyloRBT/"
  prefix: ""
  outdir: "/home/user/output/"
  thread: 1
  redo: FALSE

  # --- Input Files ---------------------------------------------
  file_refseq: ""
  file_shortreads: ""
  
  # --- Executables ---------------------------------------------
  exe_busco: ""
  exe_gff2bed: ""
  exe_samtools: ""
  exe_qualimap: ""

  exe_mafft: ""
  exe_trimal: ""
  exe_iqtree2: ""
  exe_treeshrink: ""

  # --- BUSCO Pipeline Parameters -------------------------------
  busco_lineage: ""
  busco_mode: "genome"

  thread_busco: 50
  min_busco_depth: 10

  run_trimal: FALSE
  run_treeshrink: FALSE
---

```{r, include=FALSE}
# store initial system time
sys_tic <- Sys.time()

# load libraries and function
suppressPackageStartupMessages(library(doSNOW))
suppressPackageStartupMessages(library(tidyverse))

source(file.path(path.expand(params$codedir), "data_preparation", "2_extract_busco", "functions.R"), local=TRUE)

# create outdir
currentdir <- file.path(path.expand(params$outdir), params$prefix)
if (!dir.exists(currentdir)) {
  dir.create(currentdir, recursive = T)
}

# create log file
fn_log <- file.path(currentdir, paste0(params$prefix, "_buscoextract.log"))
log_appender <- log4r::file_appender(fn_log, append=TRUE, layout=log4r::default_log_layout())
fn_logger <- log4r::logger(threshold="INFO", appenders=log_appender)
if (params$redo) {
  unlink(fn_log)
}

if (!file.exists(fn_log)) {
  readr::write_lines(c("####################################",
                       "####      BUSCO Extraction      ####",
                       "####################################"), file=fn_log)
}

knitr::opts_knit$set(root.dir = currentdir)
```

```{r child = file.path(path.expand(params$codedir), "data_preparation", "2_extract_busco", "2_refseq.Rmd")}
```

```{r child = file.path(path.expand(params$codedir), "data_preparation", "2_extract_busco", "3_shortreads.Rmd")}
```

```{r child = file.path(path.expand(params$codedir), "data_preparation", "2_extract_busco", "4_gene_trees.Rmd")}
```

```{r, include=FALSE}
# store final system time
sys_toc <- Sys.time()

# write the system time in log file
readr::write_lines(c("", paste0("Total elapsed time: ", round(as.numeric(difftime(sys_toc, sys_tic, units = "mins")), 3), " mins")),
                   file=fn_log, append=T)
```