---
title: "BUSCO Check for Reference Sequences Bias"
author: "Jeremias Ivan"
date: "`r format(Sys.time(), '%d %B %Y, %H:%M%p')`"

output:
  html_document:
    code_folding: show
    toc: true
    toc_float: true

params:
  # general
  codedir: "~/BusIER/codes"
  prefix: ""
  outdir: "~/busco"
  thread: 50
  redo: TRUE

  # input files
  file_refseq: ""
  file_shortreads: ""
  file_genome_treefile: ""
  file_buscotree: ""
  
  # executables
  exe_busco: ""
  exe_gffread: ""
  exe_gff2bed: ""
  exe_samtools: ""

  exe_mafft: ""
  exe_iqtree2: ""
  exe_treeshrink: ""
  exe_astral: ""

  # BUSCO analyses
  busco_lineage: ""
  busco_mode: "genome"
  type: "coordinate"

  thread_busco: 50
  min_busco_depth: 10
  max_busco_depth: 40

  busco_tree_mode: "control"
  busco_tree_random_ref: FALSE  # only applies for busco_tree_mode == "random"
  outgroup: !r c("")

  # misc
  current_time: ""
---

## Load required libraries and functions
```{r}
source(paste0(params$codedir, "/1_data_preparation/functions.R"))
source(paste0(params$codedir, "/2_busco_check/functions.R"))

library(doSNOW)
library(dplyr)
```

```{r, include=FALSE}
# install.packages("Biostrings")
# install.packages("data.table")
# install.packages("log4r")
# install.packages("phangorn")
# install.packages("tidyverse")

# store initial system time
sys_tic <- Sys.time()

# create outdir
currentdir <- paste0(params$outdir, "/", params$prefix)
if (!dir.exists(currentdir)) {
  dir.create(currentdir, recursive = T)
}

# create directory for log files
logdir <- paste0(currentdir, "/logs/")
if (!dir.exists(logdir)) {
  dir.create(logdir, recursive = T)
}

# create log file
current_time <- params$current_time
if (current_time == "") {
  current_time <- format(Sys.time(), "%y-%m-%d %H:%M")
  current_time <- gsub("[: -]", "" , current_time, perl=TRUE)
}

fn_log <- paste0(logdir, current_time, ".bc.log")
log_appender <- log4r::file_appender(fn_log, append = TRUE, layout = log4r::default_log_layout())
fn_logger <- log4r::logger(threshold = "INFO", appenders = log_appender)
if (!file.exists(fn_log) || params$redo) {
  unlink(fn_log)
  f_write_log(fn_log=fn_log, msg="ReSelect BUSCO")
}

knitr::opts_knit$set(root.dir = currentdir)
```

```{r}
f_write_log(fn_log=fn_log, msg=paste0("- file_refseq: ", params$file_refseq))
f_write_log(fn_log=fn_log, msg=paste0("- file_shortreads: ", params$file_shortreads))
f_write_log(fn_log=fn_log, msg=paste0("- file_genome_treefile: ", params$file_genome_treefile))
f_write_log(fn_log=fn_log, msg=paste0("- file_buscotree: ", params$file_buscotree))

f_write_log(fn_log=fn_log, msg=paste0("- type: ", params$type))
f_write_log(fn_log=fn_log, msg=paste0("- min_busco_depth: ", params$min_busco_depth))
f_write_log(fn_log=fn_log, msg=paste0("- max_busco_depth: ", params$max_busco_depth))

f_write_log(fn_log=fn_log, msg=paste0("- busco_tree_mode: ", params$busco_tree_mode))
f_write_log(fn_log=fn_log, msg=paste0("- busco_tree_random_ref: ", params$busco_tree_random_ref))
```

```{r child = paste0(params$codedir,"/2_busco_check/2_busco_ref.Rmd")}
```

```{r child = paste0(params$codedir,"/2_busco_check/3_summary.Rmd")}
```

```{r child = paste0(params$codedir,"/2_busco_check/4_busco_tree.Rmd")}
```

```{r, include=FALSE}
# store final system time
sys_toc <- Sys.time()

# write the system time in log file
f_write_log(fn_log=fn_log, msg=c("", paste0("Total elapsed time: ", round(as.numeric(difftime(sys_toc, sys_tic, units = "mins")), 3), " mins")))
```