---
title: "Run Coordinate-based BUSCO Analysis on Reference Sequences and Mapped Reads"
---

## Extract BUSCO based on reference coordinates
```{r check-busco-extract-reads}
f_write_log(fn_log=fn_log, msg=c("", "------------ Mapped Reads ----------"))

# output data.table
df_chr_busco <- data.table::data.table(ref=character(), read=character(), busco=character(), is_error=logical())

# create doSNOW cluster
nwcl <- makeCluster(params$thread)
doSNOW::registerDoSNOW(nwcl)

# iterate over short reads
for (prefix in ls_prefix) {
    # create outdir
    dir_busco_out <- paste0(dir_busco_read, prefix, "/")
    if (!dir.exists(dir_busco_out)) {
        dir.create(dir_busco_out, recursive=T)
    }

    # extract short read and reference sequence IDs
    read <- unlist(strsplit(prefix, split="--"))[1]
    ref <- unlist(strsplit(prefix, split="--"))[2]

    # check input files
    file_fas <- paste0(dir_readmap, prefix, "/", prefix, ".fa")
    if (!file.exists(file_fas)) {
        log4r::warn(fn_logger, paste0("File not found: FASTA file for ", prefix, ". Skipped."))
        next
    }

    # iterate over shared BUSCOs
    df_output_temp <- foreach (busco = shared_busco, .combine='rbind') %dopar% {
        require(Biostrings)
        require(stringr)

        # input files
        file_bam <- paste0(dir_readmap, prefix, "/", prefix, ".bam")
        file_busco_gff_out <- paste0(dir_busco_ref, ref, "/fasta/", busco, ".gff")
        file_busco_bed_out <- paste0(dir_busco_ref, ref, "/fasta/", busco, ".bed")
        if (!all(file.exists(file_busco_gff_out, file_busco_bed_out))) {
            log4r::warn(fn_logger, msg=paste0("File not found: ", busco, " GFF or BED for ", ref, ". Skipped."))
            return(data.table::data.table(ref=ref, read=read, busco=busco, is_error=TRUE))
        }

        # output files
        file_busco_cds <- paste0(dir_busco_out, busco, ".cds.fna")
        file_busco_concat <- paste0(dir_busco_out, busco, ".fna")

        # check if file exists
        if (file.exists(file_busco_concat) && file.size(file_busco_concat) != 0L && !params$redo) {
            return(data.table::data.table(ref=ref, read=read, busco=busco, is_error=FALSE))
        }

        # calculate read depth
        read_coverage <- f_calculate_read_coverage(file_bam, file_busco_bed_out, params$exe_samtools)
        if (is.null(read_coverage) || is.na(read_coverage)) {
            log4r::warn(fn_logger, msg=paste("Warn:", busco, "for", prefix, "has invalid coverage"))
        } else if (read_coverage >= params$min_busco_depth && read_coverage <= params$max_busco_depth) {
            f_extract_fasta_from_gff(file_fas, file_busco_gff_out, file_busco_cds, file_busco_concat, params$exe_gffread)
            return(data.table::data.table(ref=ref, read=read, busco=busco, is_error=FALSE))
        } else if (read_coverage < params$min_busco_depth || read_coverage > params$max_busco_depth) {
            log4r::warn(fn_logger, msg=paste("Warn:", busco, "for", prefix, "has average CDS read depth of", read_coverage))
        }

        # write log file
        return(data.table::data.table(ref=ref, read=read, busco=busco, is_error=TRUE))
    }

    # update data.table
    df_chr_busco <- rbind(df_chr_busco, df_output_temp)

    log4r::info(fn_logger, paste0("File created/modified: BUSCO FASTA alignments for ", prefix, "."))
}

stopCluster(nwcl)

# save the output file
if (is.null(df_mapped_reads_busco) || params$redo) {
    df_mapped_reads_busco <- df_chr_busco
    data.table::fwrite(df_chr_busco, file=fn_mapped_reads_busco, sep="\t", quote=F)

    if (!params$include_incomplete) {
        ls_problematic_busco <- unique(df_chr_busco$busco[df_chr_busco$is_error])
        shared_busco <- shared_busco[!shared_busco %in% ls_problematic_busco]
    } else {
        # count the number of errors per BUSCO
        df_mapped_reads_busco_count <- df_chr_busco %>%
            group_by(busco,read) %>%
            summarise(n_ref=sum(ifelse(!error, 1, 0))) %>%
            group_by(busco) %>%
            summarise(n_read=sum(ifelse(n_ref>0, 1, 0)))
        
        # update the BUSCO list
        ls_problematic_busco <- unique(df_mapped_reads_busco_count$busco[df_mapped_reads_busco_count$n_read < params$min_taxa])
        shared_busco <- shared_busco[!shared_busco %in% ls_problematic_busco]
    }
}

# print the number of BUSCO in HTML document
cat(paste("Number of shared BUSCO after filtering low-coverage genes:", length(shared_busco)))

# stop the knit if shared busco is zero
if (length(shared_busco) == 0) {
    knitr::knit_exit()
}
```

## Convert individual BUSCO alignments into MSA
```{r check-busco-msa}
# create doSNOW cluster
nwcl <- makeCluster(params$thread)
doSNOW::registerDoSNOW(nwcl)

# iterate over shared BUSCOs
output <- foreach (busco = shared_busco, .combine='c') %dopar% {
    dir_output <- paste0(dir_busco_tree, busco, "/")
    if (!dir.exists(dir_output)) {
        dir.create(dir_output, recursive=T)
    }

    # output MSA file
    fn_out <- paste0(dir_output, busco, ".fa")
    fn_out_aligned <- paste0(dir_output, busco, "_aligned.fa")
    if (all(file.exists(fn_out, fn_out_aligned)) && !params$redo) {
        # check if file is not empty
        if (file.size(fn_out_aligned) != 0L) {
            return(NULL)
        }
    }

    # extract BUSCO alignment from reference sequences
    for (ref in ls_refseq) {
        file_busco_ref <- paste0(dir_busco_ref, ref, "/fasta/", busco, ".fna")
        if (!file.exists(file_busco_ref)) {
            next
        }

        f_fasta2msa(file_busco_ref, ref, fn_out)
    }

    # extract BUSCO alignment from short reads
    count_unavailable_prefix <- 0
    for (read in ls_prefix) {
        file_busco_read <- paste0(dir_busco_read, read, "/", busco, ".fna")
        if (!file.exists(file_busco_read)) {
            count_unavailable_prefix <- count_unavailable_prefix + 1
            next
        }

        f_fasta2msa(file_busco_read, read, fn_out)
    }

    # align using MAFFT FFT-NS-2
    f_mafft(fn_out, fn_out_aligned, "--retree 2", params$exe_mafft)

    # return BUSCOs with zero mapped reads
    if (count_unavailable_prefix == length(ls_prefix)) {
        return(busco)
    }
}

stopCluster(nwcl)

# update the number of shared BUSCOs
shared_busco <- shared_busco[!shared_busco %in% output]

# print the number of BUSCO in HTML document
cat(paste("Number of shared BUSCO after filtering reference-only genes:", length(shared_busco)))
f_write_log(fn_log=fn_log, msg=c("", paste0("Number of BUSCO after filtering genes with zero mapped reads: ", length(shared_busco), ".")))

# stop the knit if shared busco is zero
if (length(shared_busco) == 0) {
    knitr::knit_exit()
}
```