---
title: "Run BUSCO Pipeline on Individual Reference Sequences and Mapped Reads"
---

## Run BUSCO on mapped reads
```{r, include=FALSE}
f_write_log(fn_log=fn_log, msg=c("", "------------ Mapped Reads ----------"))

# set up variables
is_busco_read <- FALSE

ls_busco_read_done <- c()
ls_busco_read_run <- c()

# iterate over mapped sequences
if (params$redo) {
    ls_busco_read_run <- ls_prefix
} else {
    for (read in ls_prefix) {
        # check if BUSCO run exists
        file_busco_log <- paste0(dir_busco_read, read, "/logs/busco.log")
        if (file.exists(file_busco_log)) {
            finish_msg <- system(paste("grep 'BUSCO analysis done'", file_busco_log), intern=T)
            if (length(finish_msg) != 0) {
                ls_busco_read_done <- c(ls_busco_read_done, paste("-", read))
                next
            }
        }

        # add mapped sequence to to-do-list
        ls_busco_read_run <- c(ls_busco_read_run, read)
    }
}

# output log file for available mapped sequence BUSCO runs
if (length(ls_busco_read_done) > 0) {
    ls_busco_read_done <- c(paste0("Available mapped sequence BUSCO runs (", length(ls_busco_read_done), "/", length(ls_prefix), ")"), ls_busco_read_done, "")
    f_write_log(fn_log=fn_log, msg=ls_busco_read_done)
}

# update variable for the next analysis
if (length(ls_busco_read_run) > 0) {
    is_busco_read <- TRUE
}
```

```{r}
# print the number of available mapped reads BUSCO in HTML document
cat(paste0("Available mapped reads BUSCO (", length(ls_busco_read_done), "/", length(ls_prefix), ")"))
cat(paste("Mapped reads BUSCO to run:", length(ls_busco_read_run)))
```

```{r check-busco-read-p, include=is_busco_read, eval=is_busco_read}
f_write_log(fn_log=fn_log, msg=paste("Running BUSCO using", thread_busco, "threads"))

# create doSNOW cluster
nwcl <- makeCluster(floor(params$thread/thread_busco))
doSNOW::registerDoSNOW(nwcl)

# iterate over mapped reads
foreach (prefix = ls_busco_read_run) %dopar% {
    # input FASTA file
    file_read <- paste0(dir_readmap, prefix, "/", prefix, ".fa")

    # run BUSCO
    f_run_busco(file_read, dir_lineage, prefix, dir_busco_read, params$busco_mode, thread_busco, params$exe_busco)
    log4r::info(fn_logger, paste0("File created: BUSCO run for ", prefix, "."))
}

stopCluster(nwcl)
```

## Extract common BUSCOs between reference sequences and mapped reads
```{r check-busco-common-p}
# output data.table
df_chr_busco <- data.table::data.table(ref=character(), read=character(), busco=character(), is_error=logical())

# iterate over mapped reads
for (prefix in ls_prefix) {
  # directory for BUSCO alignments
  dir_buscos <- paste0(dir_busco_read, prefix, "/run_", params$busco_lineage, "/busco_sequences/single_copy_busco_sequences/")
  
  # extract short read and reference sequence IDs
  read <- unlist(strsplit(prefix, split="--"))[1]
  ref <- unlist(strsplit(prefix, split="--"))[2]

  # remove file extension .fna
  busco_ids <- list.files(dir_buscos, pattern = "*.fna$", full.names = F, recursive = F)
  busco_ids <- sapply(busco_ids, function(x) { gsub(".fna", "", x) })
  
  # update data.table
  df_chr_busco_temp <- data.table::data.table(ref=rep(ref,length(busco_ids)),
                                              read=rep(read,length(busco_ids)),
                                              busco=busco_ids,
                                              is_error=rep(FALSE, length(busco_ids)))
  df_chr_busco <- rbind(df_chr_busco, df_chr_busco_temp)
}

# update the number of BUSCO
if (is.null(df_mapped_reads_busco) || params$redo) {
    df_mapped_reads_busco <- df_chr_busco
    data.table::fwrite(df_chr_busco, file=fn_mapped_reads_busco, sep="\t", quote=F)

    if (!params$include_incomplete) {
        ls_problematic_busco <- unique(df_chr_busco$busco[df_chr_busco$is_error])
        shared_busco <- shared_busco[!shared_busco %in% ls_problematic_busco]
    } else {
        # count the number of errors per BUSCO
        df_mapped_reads_busco_count <- df_chr_busco %>%
            group_by(busco,read) %>%
            summarise(n_ref=sum(ifelse(!is_error, 1, 0))) %>%
            group_by(busco) %>%
            summarise(n_read=sum(ifelse(n_ref>0, 1, 0)))
        
        # update the BUSCO list
        ls_problematic_busco <- unique(df_mapped_reads_busco_count$busco[df_mapped_reads_busco_count$n_read < params$min_taxa])
        shared_busco <- shared_busco[!shared_busco %in% ls_problematic_busco]
    }
}

# print the number of BUSCO in HTML document
cat(paste("Number of shared BUSCO between reference and mapped reads:", length(shared_busco)))

# check if shared BUSCOs found
if (length(shared_busco) == 0) {
    log4r::error(fn_logger, paste0("Error: no BUSCO shared between sequences. Exited."))
    knitr::knit_exit()
} else {
    f_write_log(fn_log=fn_log, msg=c("", paste0("Updated number of complete single-copy BUSCOs: ", length(shared_busco), ".")))
}
```

## Convert individual BUSCO alignments into MSA
```{r check-busco-msa-p}
# create doSNOW cluster
nwcl <- makeCluster(params$thread)
doSNOW::registerDoSNOW(nwcl)

# iterate over shared BUSCOs
foreach (busco = shared_busco) %dopar% {
    dir_output <- paste0(dir_busco_tree, busco, "/")
    if (!dir.exists(dir_output)) {
        dir.create(dir_output, recursive=T)
    }

    # output MSA file
    fn_out <- paste0(dir_output, busco, ".fa")
    fn_out_aligned <- paste0(dir_output, busco, "_aligned.fa")
    if (all(file.exists(fn_out, fn_out_aligned)) && !params$redo) {
        # check if file is not empty
        if (file.size(fn_out_aligned) != 0L) {
            return(NULL)
        }
    }

    # extract BUSCO alignment from reference sequences
    for (ref in ls_refseq) {
        file_busco_ref <- paste0(dir_busco_ref, ref, "/run_", params$busco_lineage, "/busco_sequences/single_copy_busco_sequences/", busco, ".fna")
        if (!file.exists(file_busco_ref)) {
            next
        }

        f_fasta2msa(file_busco_ref, ref, fn_out)
    }

    # extract BUSCO alignment from short reads
    for (read in ls_prefix) {
        file_busco_read <- paste0(dir_busco_read, read, "/run_", params$busco_lineage, "/busco_sequences/single_copy_busco_sequences/", busco, ".fna")
        if (!file.exists(file_busco_read)) {
            next
        }

        f_fasta2msa(file_busco_read, read, fn_out)
    }

    # align using MAFFT FFT-NS-2
    f_mafft(fn_out, fn_out_aligned, "--retree 2", params$exe_mafft)
}

stopCluster(nwcl)
```