---
title: "Summarise BUSCO Trees"
---

```{r check-summary-setup, include=FALSE}
f_write_log(fn_log=fn_log,
            msg=c("", "####################################",
                      "####           Summary          ####",
                      "####################################"))

# load ggplot2 library
library(ggplot2)

# set up color scheme for plotting
ls_colour_scheme <- RColorBrewer::brewer.pal(ifelse(length(ls_shortreads)>=3, length(ls_shortreads), 3), "Set1")

ls_colour_scheme_read <- list()
for (i in 1:length(ls_shortreads)) {
    ls_colour_scheme_read[[ls_shortreads[i]]] <- ls_colour_scheme[i]
}

# output directories
dir_check_summary <- paste0(dir_busco, "summary/")
dir_check_summary_correlation <- paste0(dir_check_summary, "correlation_figs/")
for (read in ls_shortreads) {
    dir_check_summary_correlation_read <- paste0(dir_check_summary_correlation, read)
    if (!dir.exists(dir_check_summary_correlation_read)) {
        dir.create(dir_check_summary_correlation_read, recursive=T)
    }
}

# output files
fn_prefix <- paste0(dir_check_summary, params$prefix)
# fn_ref_summary <- paste0(fn_prefix, ".ref.sumtable")
# fn_read_summary <- paste0(fn_prefix, ".read.sumtable")
fn_cor_summary <- paste0(fn_prefix, ".cor.sumtable")
# fn_chr_summary <- paste0(fn_prefix, ".chr.sumtable")

fn_dist_tiff <- paste0(dir_check_summary, params$prefix, ".dist.tiff")
```

```{r check-summary-busco-update, include=FALSE}
# create a new vector to store the list of BUSCOs
shared_busco_filtered <- shared_busco

# iterate over BUSCOs
for (busco in shared_busco_filtered) {
    # check if treefile exists
    fn_tree <- paste0(dir_busco_tree, busco, "/", busco, "_aligned.fa.treefile")
    if (!file.exists(fn_tree)){
        shared_busco_filtered <- shared_busco_filtered[shared_busco_filtered != busco]

        log4r::info(fn_logger, paste0("File not found: BUSCO tree for ", busco, ". Removed from analysis."))
        next
    }

    # read tree
    tre <- ape::read.tree(fn_tree)
    ls_tips <- tre$tip.label

    # extract reference tips
    output <- tryCatch({
        ape::keep.tip(tre, ls_refseq)
    }, error = function(err) {
        return(err)
    })

    # remove BUSCO if reference sequences are incomplete
    if (all(class(output) != "phylo")) {
        shared_busco_filtered <- shared_busco_filtered[shared_busco_filtered != busco]
        log4r::info(fn_logger, paste0("Error: incomplete references for ", busco, " tree. Removed from analysis."))
    }
}

# check if list is of length zero
if (length(shared_busco_filtered) == 0) {
    log4r::error(fn_logger, "Error: list of BUSCO is of length zero. Exited.")
    knitr::knit_exit()
}
```

## Check reference bias on BUSCO trees
```{r check-summary-tree, eval=FALSE}
# create doSNOW cluster
nwcl <- makeCluster(params$thread)
doSNOW::registerDoSNOW(nwcl)

ls_output <- foreach (busco = shared_busco_filtered, .combine='c') %dopar% {
    # initiate variable
    ref_out <- list(busco=busco)
    read_out <- list(busco=busco)

    # check if treefile exists
    fn_tree <- paste0(dir_busco_tree, busco, "/", busco, "_aligned.fa.treefile")

    # read tree
    tre <- ape::read.tree(fn_tree)
    ls_tips <- tre$tip.label

    # extract reference topology
    topology_ref <- ape::keep.tip(tre, ls_refseq)
    topology_ref$edge.length <- NULL

    # iterate over reference sequences
    for (ref in ls_refseq) {
        # extract list of taxa with specific reference
        ls_taxa <- ls_tips[stringr::str_detect(ls_tips, ref)]
        if (length(ls_taxa) <= 1) {
            ref_out[[ls_species_name[ref]]] <- "INVALID"
            next
        } else if (length(ls_shortreads)+1 > length(ls_taxa)) {
            ref_out[[ls_species_name[ref]]] <- "INCOMPLETE"
            next
        }

        # check if reference-based clade is monophyletic
        is_monophyletic <- ape::is.monophyletic(tre, tips = ls_taxa)
        if (is_monophyletic) {
            ref_out[[ls_species_name[ref]]] <- "REFBIAS"
            next
        }

        ref_out[[ls_species_name[ref]]] <- ""
    }

    # iterate over short reads
    for (read in ls_shortreads) {
        # extract list of taxa with specific reference
        ls_taxa <- ls_tips[stringr::str_detect(ls_tips, read)]
        if (length(ls_taxa) <= 1) {
            read_out[[ls_species_name[read]]] <- "INVALID"
            next
        } else if (length(ls_refseq) > length(ls_taxa)) {
            read_out[[ls_species_name[read]]] <- "INCOMPLETE"
            next
        }

        # check if reference-based clade is monophyletic
        is_monophyletic <- ape::is.monophyletic(tre, tips = ls_taxa)
        if (is_monophyletic) {
            read_out[[ls_species_name[read]]] <- "PERFECT"
            next
        }

        # check for topology-based reference bias
        topology_read <- ape::keep.tip(tre, ls_taxa)
        topology_read$edge.length <- NULL
        topology_read$tip.label <- gsub(".*--", "", topology_read$tip.label)

        if (ape::all.equal.phylo(topology_ref, topology_read)) {
            read_out[[ls_species_name[read]]] <- "TOPBIAS"
            next
        }

        read_out[[ls_species_name[read]]] <- ""
    }

    return(list(ref_out=ref_out, read_out=read_out))
}

stopCluster(nwcl)

# convert list into dataframe
ls_ref_out <- ls_output[names(ls_output)=="ref_out"]
ls_read_out <- ls_output[names(ls_output)=="read_out"]

# save the dataframes as TSV
df_ref_output <- data.table::as.data.table(do.call(rbind, ls_ref_out), fill=TRUE)
data.table::fwrite(df_ref_output, file=fn_ref_summary, sep="\t", quote=F, row.names=F)

df_read_output <- data.table::as.data.table(do.call(rbind, ls_read_out), fill=TRUE)
data.table::fwrite(df_read_output, file=fn_read_summary, sep="\t", quote=F, row.names=F)

log4r::info(fn_logger, "File created: summary for BUSCO trees.")
```

## Calculate MNTD on BUSCO trees
```{r check-summary-mntd, eval=FALSE}
# run MNTD without reference sequence
prefix <- paste0(dir_check_summary, params$prefix)
f_run_mntd(shared_busco_filtered, ls_shortreads, dir_busco_tree, ls_species_name, prefix, params$thread)
```

## Calculate phylogenetic distance between mapped reads and reference from the same taxon
```{r check-summary-individual}
# extract representative species
df_reads_ref <- data.table::data.table(species=character(), reads=character(), ref=character())

df_reads_subset <- df_reads[df_reads$is_check,]
for (i in 1:nrow(df_reads_subset)) {
    species_name <- df_reads_subset$species[i]

    # extract reference ID
    ref_id <- df_refs$id[df_refs$species == species_name]

    # update data.frame
    df_reads_ref <- rbind(df_reads_ref, data.table::data.table(species=species_name, reads=df_reads_subset$id[i], ref=ref_id))
}

# create doSNOW cluster
nwcl <- makeCluster(params$thread)
doSNOW::registerDoSNOW(nwcl)

# iterate over BUSCOs
ls_output <- foreach (busco = shared_busco_filtered, .combine='c') %dopar% {
    # check if treefile exists
    fn_tree <- paste0(dir_busco_tree, busco, "/", busco, "_aligned.fa.treefile")

    # read tree
    tre <- ape::read.tree(fn_tree)
    ls_tips <- tre$tip.label

    # calculate phylogenetic distance
    distance_tre <- ape::cophenetic.phylo(tre)

    # iterate over reads
    ls_dist <- c()
    for (i in 1:nrow(df_reads_ref)) {
        ls_dist <- c(ls_dist, distance_tre[rownames(distance_tre)==paste0(df_reads_ref$reads[i],"--",df_reads_ref$ref[i]),
                                           colnames(distance_tre)==df_reads_ref$ref[i]])
    }
    
    return(ls_dist)
}

stopCluster(nwcl)

# visualization
tiff(file=fn_dist_tiff, units="px", width=2880, height=1800)
print(ggplot(data.frame(ls_output), aes(x=ls_output, xmin=0, xmax=max(ls_output))) + 
    geom_histogram(bins = 100) +
    ggtitle("BUSCO Phylogenetic Distance between Mapped Reads and Reference") + ylab("Count") +
    theme(plot.title = element_text(hjust=0.5, size=50),
        plot.margin = margin(1.25, 1.25, 1.25, 1.25, "cm"),
        axis.text.x = element_text(size=30),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size=30),
        axis.title.y = element_text(size=40, margin=margin(t=0, r=20, b=0, l=0)),
        legend.position = "none"))
dev.off()
```

## Correlation analysis on BUSCO phylogenetic distances
```{r check-summary-correlation}
# create doSNOW cluster
nwcl <- makeCluster(params$thread)
doSNOW::registerDoSNOW(nwcl)

# iterate over BUSCOs
ls_output <- foreach (busco = shared_busco_filtered, .combine='c') %dopar% {
    library(ggplot2)
    library(ggrepel)

    # output variables
    read_out <- list(busco=busco)
    ref_out <- list()

    # check if treefile exists
    fn_tree <- paste0(dir_busco_tree, busco, "/", busco, "_aligned.fa.treefile")

    # read tree
    tre <- ape::read.tree(fn_tree)
    ls_tips <- tre$tip.label

    # calculate phylogenetic distance
    distance_tre <- ape::cophenetic.phylo(tre)

    # update list of reference and mapped reads
    ls_shortreads_available <- sapply(ls_tips, function(x) { ls_shortreads[grep(x, ls_shortreads)] })
    ls_shortreads_available <- Filter(function(x) length(x) > 0, ls_shortreads_available)
    ls_refseq_available <- ls_refseq[ls_refseq %in% ls_tips]

    # iterate over short reads
    for (read in names(ls_shortreads_available)) {
        # initiate variables
        dir_temp_fig <- paste0(dir_check_summary_correlation, read, "/")
        ref_out[[read]] <- list(busco=busco)

        # temporary data.table
        temp_df_dist <- data.table::data.table(read=character(), ref=character(), ref_dist=numeric(), read_dist=numeric())

        # extract taxa list
        read_species_name <- df_reads_ref$species[df_reads_ref$reads==read]
        read_ref_id <- df_refs$id[df_refs$species==read_species_name]

        # iterate over reference sequence
        for (ref in ls_refseq_available) {
            # extract species name
            ref_species_name <- ls_species_name[ref]

            # calculate distance for reference
            ref_dist <- NULL
            if (read_species_name == ref_species_name) {
                ref_dist <- 0
            } else {
                idx_ref <- match(read_species_name, df_refs$species)
                ref_dist <- distance_tre[rownames(distance_tre)==df_refs$id[idx_ref], colnames(distance_tre)==ref]
            }

            # calculate distance for short reads
            read_dist <- distance_tre[rownames(distance_tre)==paste0(read,"--",ref), colnames(distance_tre)==read_ref_id]

            # update data.frame
            temp_df_dist <- rbind(temp_df_dist, data.table::data.table(read=read_species_name,
                                                                       ref=ref_species_name,
                                                                       ref_dist=ref_dist,
                                                                       read_dist=read_dist))
        }

        # remove NA values
        temp_df_dist <- na.omit(temp_df_dist)
        if (nrow(temp_df_dist) == 0){
            next
        }

        # run linear model
        lm_result <- lm(read_dist~ref_dist, data=temp_df_dist)
        lm_stats <- f_extract_summary_lm(lm_result)

        # set up variables
        is_problematic <- FALSE
        if (all(!is.null(lm_stats)) && lm_stats$pvalue < 0.05) {
            is_problematic <- TRUE
        }

        # check the presence of outliers
        temp_read_out <- boxplot.stats(temp_df_dist$read_dist)$out

        if (length(temp_read_out) != 0) {
            # create another data.frame to store BUSCO without outliers
            temp_df_out <- temp_df_dist[temp_df_dist$read_dist %in% temp_read_out,]
            temp_df_no_out <- temp_df_dist[!temp_df_dist$read_dist %in% temp_read_out,]

            # check if all values are the same
            if (length(unique(temp_df_no_out$read_dist)) == 1) {
                for (ref in temp_df_no_out$ref) {
                    ref_out[[read]][[ref]] <- FALSE
                }

                # outliers
                for (ref in temp_df_out$ref) {
                    ref_out[[read]][[ref]] <- paste(is_problematic, "(OUT)")
                }

            } else {
                # run linear model without outliers
                lm_result_no_out <- lm(read_dist~ref_dist, data=temp_df_no_out)
                lm_stats_no_out <- f_extract_summary_lm(lm_result_no_out)

                # check if values are NULL
                if (all(!is.null(lm_stats)) && all(!is.null(lm_stats_no_out))) {
                    for (ref in temp_df_out$ref) {
                        ref_out[[read]][[ref]] <- paste(is_problematic, "(O)")
                    }

                    # outliers
                    if ((lm_stats_no_out$pvalue >= 0.05 && is_problematic) || (lm_stats_no_out$pvalue <= 0.05 && !is_problematic)) {
                        for (ref in temp_df_no_out$ref) {
                            ref_out[[read]][[ref]] <- !is_problematic
                        }
                    } else {
                        for (ref in temp_df_no_out$ref) {
                            ref_out[[read]][[ref]] <- is_problematic
                        }
                    }
                }
            }

        } else {
            # iterate over reference sequence
            for (ref in ls_refseq_available) {
                ref_out[[read]][[ls_species_name[ref]]] <- is_problematic
            }
        }

        read_out[[read_species_name]] <- paste0(lm_stats$rsquared, " (", lm_stats$pvalue, ")")

        # visualisation
        fn_busco_tiff <- paste0(dir_temp_fig, busco, ".tiff")

        plot <- ggplot(temp_df_dist, aes(x=ref_dist, y=read_dist, color=read)) +
            geom_point(shape=16, aes(size=20)) +
            geom_smooth(method='lm', formula= y~x, aes(linewidth=4)) +
            scale_colour_manual(values=ls_colour_scheme_read[[read]])

        # add outliers label
        if (length(temp_read_out) != 0){
            plot <- plot + 
                geom_text_repel(data=temp_df_out, aes(label=ref), size=12) +
                stat_smooth(data=temp_df_no_out, geom='line', aes(x=ref_dist, y=read_dist, linewidth=4), method='lm', formula=y~x, alpha=0.5)
        }

        plot <- plot +
            ggtitle(paste("Correlation of BUSCO", busco, "Phylogenetic Distances")) +
            xlab("Reference Distance") + ylab("Short Reads Distance") +
            theme(
                plot.title = element_text(hjust = 0.5, size = 50),
                plot.margin = margin(1.25, 1.25, 1.25, 1.25, "cm"),
                axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
                axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
                axis.text.y=element_text(size=30),
                axis.text.x=element_text(size=30),
                strip.text = element_text(size = 30),
                legend.position = "none"
            )

        # save the plot
        tiff(file=fn_busco_tiff, units="px", width=1600, height=700)
        print(plot)
        dev.off()
    }

    return(list(read_out=read_out, ref_out=ref_out))
}

# convert list into dataframe
ls_ref_out <- ls_output[names(ls_output)=="ref_out"]
ls_read_out <- ls_output[names(ls_output)=="read_out"]

# save the dataframes as TSV
for (read in ls_shortreads) {
    # output file
    fn_temp_out <- paste0(fn_prefix, ".", read, ".cor.sumtable")

    # extract read-specific entries
    ls_temp_out <- lapply(ls_ref_out, function(x) { x[[read]] })
    df_temp_out <- data.table::as.data.table(do.call(rbind, ls_temp_out), fill=TRUE)

    # save file
    data.table::fwrite(df_temp_out, file=fn_temp_out, sep="\t", quote=F, row.names=F)
}

# save the data.frame
df_output <- data.table::as.data.table(do.call(rbind, ls_read_out), fill=TRUE)
data.table::fwrite(df_output, file=fn_cor_summary, sep="\t", quote=F, row.names=F)
```

```{r check-summary-chromosome, eval=FALSE}
# create doSNOW cluster
nwcl <- makeCluster(params$thread)
doSNOW::registerDoSNOW(nwcl)

# read input file
df_chromosome <- data.table::fread(params$file_refseq_chr)

# iterate over BUSCO
ls_output <- foreach (busco = shared_busco_filtered, .combine='c') %dopar% {
    # initiate variable
    ref_out <- list(busco=busco)

    # iterate over reference sequences
    for (ref in ls_refseq) {
        # BUSCO files
        file_busco_fas <- paste0(dir_busco_ref, ref, "/run_", params$busco_lineage, "/busco_sequences/single_copy_busco_sequences/", busco, ".fna")

        # extract header
        busco_header <- system(paste("grep '^>'", file_busco_fas), intern=T)
        busco_location <- unlist(strsplit(busco_header, split=">"))[2]
        seq_name <- unlist(strsplit(busco_location, split=":"))[1]

        # extract chromosome
        species_name <- ls_species_name[ref]
        idx_row <- match(seq_name, df_chromosome[[species_name]])
        if (length(idx_row) == 0) {
            ref_out[[species_name]] <- "-"
            next
        }
        
        ref_out[[species_name]] <- df_chromosome$chr[idx_row]
    }

    return(list(ref_out))
}

stopCluster(nwcl)

# create consensus column
df_output <- data.table::as.data.table(do.call(rbind, ls_output))
data.table::fwrite(df_output, file=fn_chr_summary, sep="\t", quote=F, row.names=F)

# open the file (because it does not work otherwise)
df_output <- data.table::fread(fn_chr_summary)
df_output_transform <- apply(df_output, 1, function(x) {
    most_freq <- names(which.max(table(x)))
    extract_diff <- ifelse(x == most_freq, "", x)
    c(extract_diff, consensus=most_freq)
})

df_output_transform <- t(df_output_transform)
df_output_transform <- data.table::data.table(df_output_transform)

# save the data.frame
data.table::fwrite(df_output_transform, file=fn_chr_summary, sep="\t", quote=F, row.names=F)
```