---
title: "Summarise BUSCO Trees"
---

```{r check-summary-setup, include=FALSE}
f_write_log(fn_log=fn_log,
            msg=c("", "####################################",
                      "####           Summary          ####",
                      "####################################"))

# load ggplot2 library
library(ggplot2)

# output directories
dir_check_summary <- paste0(dir_busco_b, "summary/")
dir_check_summary_mntd <- paste0(dir_check_summary, "mntd/")
dir_check_summary_mntd_noref <- paste0(dir_check_summary, "mntd_noref/")
dir_check_summary_correlation <- paste0(dir_check_summary, "correlation/")
lapply(list(dir_check_summary_mntd,dir_check_summary_mntd_noref,dir_check_summary_correlation), function(x){if(!dir.exists(x)) dir.create(x, recursive=T)})

# output files
fn_ref_summary <- paste0(dir_check_summary, params$prefix, ".ref.sumtable")
fn_read_summary <- paste0(dir_check_summary, params$prefix, ".read.sumtable")
fn_cor_summary <- paste0(dir_check_summary, params$prefix, ".cor.sumtable")

fn_dist_tiff <- paste0(dir_check_summary, params$prefix, ".dist.tiff")
```

```{r check-summary-busco-update}
# create a new vector to store the list of BUSCOs
shared_busco_filtered <- shared_busco_b

# iterate over BUSCOs
for (busco in shared_busco_filtered) {
    # check if treefile exists
    fn_tree <- paste0(dir_busco_b_tree, busco, "/", busco, "_aligned.fa.treefile")
    if (!file.exists(fn_tree)){
        shared_busco_filtered <- shared_busco_filtered[shared_busco_filtered != busco]

        log4r::info(fn_logger, paste0("File not found: BUSCO tree for ", busco, ". Removed from analysis."))
        next
    }

    # read tree
    tre <- ape::read.tree(fn_tree)
    ls_tips <- tre$tip.label

    # extract reference tips
    output <- tryCatch({
        ape::keep.tip(tre, ls_refseq)
    }, error = function(err) {
        return(err)
    })

    # remove BUSCO if reference sequences are incomplete
    if (all(class(output) != "phylo")) {
        shared_busco_filtered <- shared_busco_filtered[shared_busco_filtered != busco]
        log4r::info(fn_logger, paste0("Error: incomplete references for ", busco, " tree. Removed from analysis."))
    }
}
```

## Check reference bias on BUSCO trees
```{r check-summary-tree}
# create doSNOW cluster
nwcl <- makeCluster(params$thread)
doSNOW::registerDoSNOW(nwcl)

ls_output <- foreach (busco = shared_busco_filtered, .combine='c') %dopar% {
    # initiate variable
    ref_out <- list(busco=busco)
    read_out <- list(busco=busco)

    # check if treefile exists
    fn_tree <- paste0(dir_busco_b_tree, busco, "/", busco, "_aligned.fa.treefile")

    # read tree
    tre <- ape::read.tree(fn_tree)
    ls_tips <- tre$tip.label

    # extract reference topology
    topology_ref <- ape::keep.tip(tre, ls_refseq)
    topology_ref$edge.length <- NULL

    # iterate over reference sequences
    for (ref in ls_refseq) {
        # extract list of taxa with specific reference
        ls_taxa <- ls_tips[stringr::str_detect(ls_tips, ref)]
        if (length(ls_taxa) <= 1) {
            ref_out[[ls_species_name[ref]]] <- "INVALID"
            next
        } else if (length(ls_shortreads)+1 > length(ls_taxa)) {
            ref_out[[ls_species_name[ref]]] <- "INCOMPLETE"
            next
        }

        # check if reference-based clade is monophyletic
        is_monophyletic <- ape::is.monophyletic(tre, tips = ls_taxa)
        if (is_monophyletic) {
            ref_out[[ls_species_name[ref]]] <- "REFBIAS"
            next
        }

        ref_out[[ls_species_name[ref]]] <- ""
    }

    # iterate over short reads
    for (read in ls_shortreads) {
        # extract list of taxa with specific reference
        ls_taxa <- ls_tips[stringr::str_detect(ls_tips, read)]
        if (length(ls_taxa) <= 1) {
            read_out[[ls_species_name[read]]] <- "INVALID"
            next
        } else if (length(ls_refseq) > length(ls_taxa)) {
            read_out[[ls_species_name[read]]] <- "INCOMPLETE"
            next
        }

        # check if reference-based clade is monophyletic
        is_monophyletic <- ape::is.monophyletic(tre, tips = ls_taxa)
        if (is_monophyletic) {
            read_out[[ls_species_name[read]]] <- "PERFECT"
            next
        }

        # check for topology-based reference bias
        topology_read <- ape::keep.tip(tre, ls_taxa)
        topology_read$edge.length <- NULL
        topology_read$tip.label <- gsub(".*--", "", topology_read$tip.label)

        if (ape::all.equal.phylo(topology_ref, topology_read)) {
            read_out[[ls_species_name[read]]] <- "TOPBIAS"
            next
        }

        read_out[[ls_species_name[read]]] <- ""
    }

    return(list(ref_out=ref_out, read_out=read_out))
}

stopCluster(nwcl)

# convert list into dataframe
ls_ref_out <- ls_output[names(ls_output)=="ref_out"]
ls_read_out <- ls_output[names(ls_output)=="read_out"]

# save the dataframes as TSV
df_ref_output <- data.table::as.data.table(do.call(rbind, ls_ref_out), fill=TRUE)
data.table::fwrite(df_ref_output, file=fn_ref_summary, sep="\t", quote=F, row.names=F)

df_read_output <- data.table::as.data.table(do.call(rbind, ls_read_out), fill=TRUE)
data.table::fwrite(df_read_output, file=fn_read_summary, sep="\t", quote=F, row.names=F)

log4r::info(fn_logger, "File created: summary for BUSCO trees.")
```

## Calculate MNTD on BUSCO trees
```{r check-summary-mntd}
# run MNTD with reference sequence
prefix <- paste0(dir_check_summary_mntd, params$prefix)
f_run_mntd(shared_busco_filtered, ls_refseq, TRUE, dir_busco_b_tree, ls_species_name, prefix, params$thread)

# run MNTD without reference sequence
prefix <- paste0(dir_check_summary_mntd_noref, params$prefix)
f_run_mntd(shared_busco_filtered, ls_refseq, FALSE, dir_busco_b_tree, ls_species_name, prefix, params$thread)
```

## Calculate phylogenetic distance between mapped reads and reference from the same taxon
```{r check-summary-individual}
# extract representative species
df_reads_ref <- data.table::data.table(species=character(), reads=character(), ref=character())

df_reads_subset <- df_reads[df_reads$is_check,]
for (i in 1:nrow(df_reads_subset)) {
    species_name <- df_reads_subset$species[i]

    # extract reference ID
    ref_id <- df_refs$id[df_refs$species == species_name]

    # update data.frame
    df_reads_ref <- rbind(df_reads_ref, data.table::data.table(species=species_name, reads=df_reads_subset$id[i], ref=ref_id))
}

# create doSNOW cluster
nwcl <- makeCluster(params$thread)
doSNOW::registerDoSNOW(nwcl)

# iterate over BUSCOs
ls_output <- foreach (busco = shared_busco_filtered, .combine='c') %dopar% {
    # check if treefile exists
    fn_tree <- paste0(dir_busco_b_tree, busco, "/", busco, "_aligned.fa.treefile")

    # read tree
    tre <- ape::read.tree(fn_tree)
    ls_tips <- tre$tip.label

    # calculate phylogenetic distance
    distance_tre <- ape::cophenetic.phylo(tre)

    # iterate over reads
    ls_dist <- c()
    for (i in 1:nrow(df_reads_ref)) {
        ls_dist <- c(ls_dist, distance_tre[rownames(distance_tre)==paste0(df_reads_ref$reads[i],"--",df_reads_ref$ref[i]),
                                           colnames(distance_tre)==df_reads_ref$ref[i]])
    }
    
    return(ls_dist)
}

stopCluster(nwcl)

# visualization
tiff(file=fn_dist_tiff, units="px", width=2880, height=1800)
ggplot(data.frame(ls_output), aes(x=ls_output, xmin=0)) + 
    geom_density() +
    ggtitle("BUSCO Phylogenetic Distance between Mapped Reads and Reference") + ylab("Density") +
    theme(plot.title = element_text(hjust=0.5, size=50),
        plot.margin = margin(1.25, 1.25, 1.25, 1.25, "cm"),
        axis.text.x = element_text(size=30),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size=30),
        axis.title.y = element_text(size=40, margin=margin(t=0, r=20, b=0, l=0)),
        legend.position = "none")
dev.off()
```

```{r check-summary-correlation}
# create doSNOW cluster
nwcl <- makeCluster(params$thread)
doSNOW::registerDoSNOW(nwcl)

# iterate over BUSCOs
ls_output <- foreach (busco = shared_busco_filtered, .combine='c') %dopar% {
    library(ggplot2)
    library(ggrepel)

    # output variables
    df_dist <- data.table::data.table(read=character(), ref=character(), ref_dist=numeric(), read_dist=numeric())
    read_out <- list(busco=busco)

    # check if treefile exists
    fn_tree <- paste0(dir_busco_b_tree, busco, "/", busco, "_aligned.fa.treefile")

    # read tree
    tre <- ape::read.tree(fn_tree)
    ls_tips <- tre$tip.label

    # calculate phylogenetic distance
    distance_tre <- ape::cophenetic.phylo(tre)

    # iterate over short reads
    for (read in ls_shortreads) {
        # temporary data.table
        temp_df_dist <- data.table::data.table(read=character(), ref=character(), ref_dist=numeric(), read_dist=numeric())

        # extract taxa list
        read_species_name <- df_reads_ref$species[df_reads_ref$reads==read]

        # iterate over reference sequence
        for (ref in ls_refseq) {
            # extract species name
            ref_species_name <- ls_species_name[ref]

            # calculate distance for reference
            ref_dist <- NULL
            if (read_species_name == ref_species_name) {
                ref_dist <- 0
            } else {
                idx_ref <- match(read_species_name, df_refs$species)
                ref_dist <- distance_tre[rownames(distance_tre)==df_refs$id[idx_ref], colnames(distance_tre)==ref]
            }

            # calculate distance for short reads
            read_dist <- distance_tre[rownames(distance_tre)==paste0(read,"--",ref), colnames(distance_tre)==ref]

            # update data.frame
            temp_df_dist <- rbind(temp_df_dist, data.table::data.table(read=read_species_name,
                                                                       ref=ref_species_name,
                                                                       ref_dist=ref_dist,
                                                                       read_dist=read_dist))
        }

        # check if table is empty
        if (nrow(temp_df_dist) < 1){
            log4r::info(fn_logger, paste("Error: temporary distance table for", read, "has", nrow(temp_df_dist), "row(s). Skipped."))
            next
        }

        # run linear model
        lm_result <- lm(read_dist~ref_dist, data=temp_df_dist)
        read_out[[read_species_name]] <- paste0(round(summary(lm_result)$r.squared, 3),
                                                " (", round(summary(lm_result)$coefficients[2,4], 3), ")")

        # update data.table
        df_dist <- rbind(df_dist, temp_df_dist)
    }

    # identify outliers based on IQR criterion
    value_refs_out <- boxplot.stats(df_dist$ref_dist)$out
    value_read_out <- boxplot.stats(df_dist$read_dist)$out

    df_refs_outlier <- df_dist[df_dist$ref_dist %in% value_refs_out,]
    df_read_outlier <- df_dist[df_dist$read_dist %in% value_read_out,]

    # generate plots
    fn_busco_tiff <- paste0(dir_check_summary_correlation, busco, ".tiff")

    tiff(file=fn_busco_tiff, units="px", width=1600, height=2100)
    print(ggplot(df_dist, aes(x=ref_dist, y=read_dist, color=read)) +
        geom_point(shape=16, aes(size=20)) +
        geom_smooth(method='lm', formula= y~x, aes(linewidth=4)) +
        geom_text_repel(data=df_refs_outlier, aes(label=df_refs_outlier$ref), size=12) +
        geom_text_repel(data=df_read_outlier, aes(label=rep("READ", nrow(df_read_outlier))), size=12) +
        facet_wrap(~read, ncol=1) +
        ggtitle("Correlation of BUSCO Phylogenetic Distances") +
        xlab("Reference Distance") + ylab("Short Reads Distance") +
        theme(
            plot.title = element_text(hjust = 0.5, size = 50),
            plot.margin = margin(1.25, 1.25, 1.25, 1.25, "cm"),
            axis.title.x=element_text(size = 40, margin = margin(t=20, r=0, b=0, l=0)),
            axis.title.y=element_text(size = 40, margin = margin(t=0, r=20, b=0, l=0)),
            axis.text.y=element_text(size=30),
            axis.text.x=element_text(size=30),
            strip.text = element_text(size = 30),
            legend.position = "none"
        ))

    dev.off()

    return(list(read_out))
}

# save the data.frame
df_output <- data.table::as.data.table(do.call(rbind, ls_output), fill=TRUE)
data.table::fwrite(df_output, file=fn_cor_summary, sep="\t", quote=F, row.names=F)
```