---
title: "Calculate nRF on BUSCO Trees"
---

```{r check-run-setup, include=FALSE}
f_write_log(fn_log=fn_log,
            msg=c("", "####################################",
                      "####      Check BUSCO Trees     ####",
                      "####################################"))

# output directory
dir_check_tree <- paste0(dir_current, "/busco_check/busco_tree/")
if (!dir.exists(dir_check_tree)) {
    dir.create(dir_check_tree, recursive=T)
}

# check number of BUSCO sampling
n_busco_sampling <- params$n_busco_sampling
if (n_busco_sampling <= 0) {
    log4r::error(fn_logger, "Number of BUSCO sampling is <= 0. Exited.")
    knitr::knit_exit()
} else if (n_busco_sampling > length(shared_busco_complete)) {
    n_busco_sampling <- length(shared_busco_complete)
    f_write_log(fn_log=fn_log, msg=paste("Number of BUSCO sampling is set to be", n_busco_sampling))
}

# check input genome treefile
if (!file.exists(params$file_genome_treefile)) {
    log4r::error(fn_logger, "Genome treefile is not found. Exited.")
    knitr::knit_exit()
}
```

```{r check-run-metadata}
# read genome treefile
genome_tree <- ape::read.tree(params$file_genome_treefile)
genome_dist <- ape::cophenetic.phylo(genome_tree)

# set number of threads
nthread <- ifelse(params$thread > n_busco_sampling, n_busco_sampling, params$thread)

# create doSNOW cluster
nwcl <- makeCluster(nthread)
doSNOW::registerDoSNOW(nwcl)

# iterate over number of reference sequences
for (i in 1:length(ls_refseq)) {
    # output directory
    dir_check_tree_category <- paste0(dir_check_tree, i, "/")
    if (!dir.exists(dir_check_tree_category)) {
        dir.create(dir_check_tree_category, recursive=T)
    }

    # output file
    fn_metadata <- paste0(dir_check_tree_category, "metadata.tsv")
    if (file.exists(fn_metadata) && !params$redo) {
        next
    }

    # extract random BUSCOs
    ls_sampled_busco <- sample(shared_busco_complete, n_busco_sampling, replace = FALSE)

    # iterate over BUSCOs
    ls_output <- foreach(busco = ls_sampled_busco, .combine='rbind') %dopar% {
        # create data.table to store metadata
        df_temp <- data.table::data.table(busco=character(), read=character(), ref=character())

        # extract random refs
        ls_sampled_refs <- sample(ls_refseq, i, replace=FALSE)

        # iterate through the number of runs
        for (read in ls_shortreads) {
            # extract reference ID based on short-reads
            read_species_name <- df_reads_ref$species[df_reads_ref$reads==read]
            read_ref_id <- df_reads_ref$ref[df_reads_ref$species==read_species_name]

            # extract the closest reference
            closest_ref <- f_check_closest_ref(genome_dist, read_ref_id, ls_sampled_refs)

            # update data.table
            df_temp <- rbind(df_temp, data.table::data.table(busco=busco, read=read, ref=closest_ref))
        }

        return(df_temp)
    }

    # save data.table
    data.table::fwrite(ls_output, file=fn_metadata, sep="\t", quote=F, row.names=F)
}

stopCluster(nwcl)
```