---
title: "Read Mapping of Short Reads"
output:
  html_document:
    code_folding: show

params:
  # general
  codedir: "~/BusIER/codes"
  prefix: ""
  outdir: "~/busco"
  thread: 5
  redo: TRUE
  
  # executables
  exe_bwamem2: ""
  exe_samtools: ""
---

## Load required libraries and functions
```{r}
source(paste0(params$codedir, "/3_read_mapping/functions.R"))

library(doSNOW)
```

```{r, include=FALSE}
# install.packages("data.table")
# install.packages("log4r")

# store initial system time
sys_tic <- Sys.time()

# create outdir
currentdir <- paste0(params$outdir, "/", params$prefix)
if (!dir.exists(currentdir)) {
  dir.create(currentdir, recursive = T)
}

# create directory for log files
logdir <- paste0(currentdir, "/logs/")
if (!dir.exists(logdir)) {
  dir.create(logdir, recursive = T)
}

# create log file
fn_log <- paste0(logdir, params$prefix, ".readmap.log")
log_appender <- log4r::file_appender(fn_log, append = TRUE, layout = log4r::default_log_layout())
fn_logger <- log4r::logger(threshold = "INFO", appenders = log_appender)
if (!file.exists(fn_log) || params$redo) {
  unlink(fn_log)
  write.table("BusIER", file=fn_log, quote=F, row.names=F, col.names=F)
}

knitr::opts_knit$set(root.dir = currentdir)
```

```{r child = paste0(params$codedir,"/3_read_mapping/2_run.Rmd")}
```

```{r, include=FALSE}
# store final system time
sys_toc <- Sys.time()

# write the system time in log file
write.table(c("", paste0("Total elapsed time: ", round(as.numeric(difftime(sys_toc, sys_tic, units = "mins")), 3), " mins")),
            file=fn_log, quote=F, row.names=F, col.names=F, append=T)
```