---
title: "Data Preparation for BUSCO Checking"
author: "Jeremias Ivan"
date: "`r format(Sys.time(), '%d %B %Y, %H:%M%p')`"

output:
  html_document:
    code_folding: show
    toc: true
    toc_float: true

params:
  # general
  codedir: "~/BusIER/codes"
  prefix: ""
  outdir: "~/busco"
  thread: 50
  redo: TRUE
  
  # list of accession numbers to be downloaded
  file_refseq: ""
  file_shortreads: ""
  file_adapters: ""

  # executables
  exe_datasets: ""
  bin_sratoolkit: ""

  exe_adapterremoval: ""
  exe_bwamem2: ""
  exe_samtools: ""
  exe_bcftools: ""
  exe_qualimap: ""

  # data filtering
  min_read_quality: 25

  # number of threads
  thread_adapterremoval: 10
  thread_bwamem2: 50
  thread_samtools: 10
  thread_qualimap: 50

  # misc
  current_time: ""
---

## Load required libraries and functions
```{r}
source(paste0(params$codedir, "/1_data_preparation/functions.R"))

library(doSNOW)
```

```{r, include=FALSE}
# install.packages("data.table")
# install.packages("log4r")

# store initial system time
sys_tic <- Sys.time()

# create outdir
currentdir <- paste0(params$outdir, "/", params$prefix)
if (!dir.exists(currentdir)) {
  dir.create(currentdir, recursive = T)
}

# create directory for log files
logdir <- paste0(currentdir, "/logs/")
if (!dir.exists(logdir)) {
  dir.create(logdir, recursive = T)
}

# create log file
current_time <- params$current_time
if (current_time == "") {
  current_time <- format(Sys.time(), "%y-%m-%d %H:%M")
  current_time <- gsub("[: -]", "" , current_time, perl=TRUE)
}

fn_log <- paste0(logdir, current_time, ".dp.log")
log_appender <- log4r::file_appender(fn_log, append = TRUE, layout = log4r::default_log_layout())
fn_logger <- log4r::logger(threshold = "INFO", appenders = log_appender)
if (!file.exists(fn_log) || params$redo) {
  unlink(fn_log)
  f_write_log(fn_log=fn_log, msg="BusIER")
}

knitr::opts_knit$set(root.dir = currentdir)
```

```{r child = paste0(params$codedir,"/1_data_preparation/2_download.Rmd")}
```

```{r child = paste0(params$codedir,"/1_data_preparation/3_readmap.Rmd")}
```

```{r, include=FALSE}
# store final system time
sys_toc <- Sys.time()

# write the system time in log file
f_write_log(fn_log=fn_log, msg=c("", paste0("Total elapsed time: ", round(as.numeric(difftime(sys_toc, sys_tic, units = "mins")), 3), " mins")))
```