---
title: "Tree Topology Test"
---

```{r, include=FALSE}
readr::write_lines(c("", "--------- Tree Topology Test -------"),
                   file=fn_log, append=T)

# output directory
dir_locustree <- file.path(dir_check_summary, "topology_test")
if (params$is_astral_constrained && file.exists(params$file_species_treefile)) {
    dir_locustree <- file.path(dir_check_summary, "topology_test_constrained")
}

if (!dir.exists(dir_locustree)) {
    dir.create(dir_locustree, recursive=T)
}

# input files
fn_cor_summary <- file.path(dir_check_summary, paste0(params$prefix, ".cor.sumtable"))
df_cor_summary <- data.table::fread(fn_cor_summary)

# output files
fn_cf_summary <- file.path(dir_locustree, paste0(params$prefix, ".cf.sumtable"))
```

## Tree topology test
```{r topology-test, include=FALSE}
# iterate over short-reads
for (read in ls_shortreads) {
    # output directory
    dir_output_read <- file.path(dir_locustree, read)

    # subset the data.frame
    df_cor_subset <- df_cor_summary[df_cor_summary$read==read,]

    # iterate over sets of locus
    for (condition in c("all", "bias", "nonbias")) {
        # create output directories
        dir_output_condition <- file.path(dir_output_read, condition)
        dir_output_condition_fasta <- file.path(dir_output_condition, "alignment")
        dir_output_condition_trees <- file.path(dir_output_condition, "trees")
        lapply(list(dir_output_condition_fasta,dir_output_condition_trees), function(x){
            if(!dir.exists(x)) dir.create(x, recursive=T)})

        # list locus
        ls_locus_condition <- df_cor_subset$locus
        if (condition == "bias") {
            ls_locus_condition <- df_cor_subset$locus[df_cor_subset$lm_p<0.05 | df_cor_subset$spearman_p<0.05]
        } else if (condition == "nonbias") {
            ls_locus_condition_bias <- df_cor_subset$locus[df_cor_subset$lm_p<0.05 | df_cor_subset$spearman_p<0.05]
            ls_locus_condition <- df_cor_subset$locus[!df_cor_subset$locus%in%ls_locus_condition_bias]
        }

        # remove NAs
        ls_locus_condition <- ls_locus_condition[!is.na(ls_locus_condition)]

        # output files
        fn_locus_condition_prefix <- file.path(dir_output_condition_trees, "all_locus")
        fn_locus_condition_treefile <- paste0(fn_locus_condition_prefix, ".treefile")
        
        fn_locus_condition_astral_treefile <- file.path(dir_output_condition_trees, "astral.treefile")
        fn_locus_condition_astral_log <- file.path(dir_output_condition_trees, "astral.log")
        fn_locus_condition_gcf_treefile <- file.path(dir_output_condition_trees, "gcf.cf.tree")
        fn_locus_condition_scf_treefile <- file.path(dir_output_condition_trees, "scf.cf.tree")
        if (all(file.exists(fn_locus_condition_astral_treefile, fn_locus_condition_gcf_treefile, fn_locus_condition_scf_treefile)) && !params$redo) {
            next
        }

        # create doSNOW cluster
        nwcl <- makeCluster(params$thread)
        doSNOW::registerDoSNOW(nwcl)

        # iterate over all locus
        foreach(locus = ls_locus_condition) %dopar% {
            # extract alignment
            fn_input <- file.path(params$dir_genes_alignment, locus, paste0(locus, ".fa"))
            fn_output <- file.path(dir_output_condition_fasta, paste0(locus, ".fa"))
            if (file.exists(fn_output)) {
                return(NULL)
            }

            # extract headers
            ls_prefix_subset <- ls_prefix[grepl(paste0("^",read,"--"), ls_prefix)]
            ls_header <- c(ls_refseq, ls_prefix_subset)

            f_extract_fasta(fn_input, ls_header, fn_output)
        }

        stopCluster(nwcl)

        # run IQ-TREE2
        f_multiple_tree(dir_output_condition_fasta, fn_locus_condition_prefix, params$thread, params$redo, params$exe_iqtree2)
        alltre_temp <- ape::read.tree(fn_locus_condition_treefile)
        alltre_temp <- alltre_temp[[1]]

        # run ASTRAL
        if (params$is_astral_constrained && file.exists(params$file_species_treefile)) {
            fn_sptree <- file.path(dir_output_condition_trees, "sptree.treefile")
            
            # open species tree
            sptree <- ape::read.tree(params$file_species_treefile)
            sptree <- ape::drop.tip(sptree, tip=sptree$tip.label[!sptree$tip.label%in%alltre_temp$tip.label])
            ape::write.tree(sptree, file=fn_sptree)

            f_astral_constrained(fn_locus_condition_treefile, fn_locus_condition_astral_treefile, fn_locus_condition_astral_log, fn_sptree, params$exe_astral)

        } else {
            f_astral(fn_locus_condition_treefile, fn_locus_condition_astral_treefile, fn_locus_condition_astral_log, params$exe_astral)
        }
        
        # calculate sCF and gCF
        f_calculate_cf(fn_locus_condition_treefile, fn_locus_condition_astral_treefile, dir_output_condition_fasta, dir_output_condition_trees, params$thread, params$exe_iqtree2)

        log4r::info(fn_logger, paste0("Finished running tree topology test on ", condition, " trees for ", read, "."))
    }
}
```

```{r, results='asis', echo=FALSE}
# print trees in HTML
for (reads in ls_shortreads) {
    cat(sprintf("\n### %s\n\n", reads))
    
    # input files
    fn_tree_all <- file.path(dir_locustree, reads, "all", "trees", "astral.treefile")
    fn_tree_bias <- file.path(dir_locustree, reads, "bias", "trees", "astral.treefile")
    fn_tree_nonbias <- file.path(dir_locustree, reads, "nonbias", "trees", "astral.treefile")

    # set the number of columns
    par(mfrow = c(1, 3))
    plot(ape::read.tree(fn_tree_all), main = "All loci", cex = 0.8)
    plot(ape::read.tree(fn_tree_bias), main = "Putatively biased loci", cex = 0.8)
    plot(ape::read.tree(fn_tree_nonbias), main = "Putatively unbiased loci", cex = 0.8)
    par(mfrow = c(1, 1))
}
```

```{r topology-test-perref, include=FALSE}
# iterate over shortreads
for (read in ls_shortreads) {
    # subset the data.frame
    df_cor_subset <- df_cor_summary[df_cor_summary$read==read,]

    # iterate over sets of locus
    for (condition in c("all", "bias", "nonbias")) {
        # create output directories
        dir_output_condition_ref <- file.path(dir_locustree, read, condition, "per_reference")

        # list locus
        ls_locus_condition <- df_cor_subset$locus
        if (condition == "bias") {
            ls_locus_condition <- df_cor_subset$locus[df_cor_subset$lm_p<0.05 | df_cor_subset$spearman_p<0.05]
        } else if (condition == "nonbias") {
            ls_locus_condition_bias <- df_cor_subset$locus[df_cor_subset$lm_p<0.05 | df_cor_subset$spearman_p<0.05]
            ls_locus_condition <- df_cor_subset$locus[!df_cor_subset$locus%in%ls_locus_condition_bias]
        }

        # remove NAs
        ls_locus_condition <- ls_locus_condition[!is.na(ls_locus_condition)]

        # iterate over reference sequences
        for (ref in ls_refseq) {
            dir_output_perref <- file.path(dir_output_condition_ref, ref)
            dir_output_perref_fasta <- file.path(dir_output_perref, "alignment")
            dir_output_perref_trees <- file.path(dir_output_perref, "trees")
            lapply(list(dir_output_perref_fasta,dir_output_perref_trees), function(x){
                if(!dir.exists(x)) dir.create(x, recursive=T)})

            # output files
            fn_locus_perref_prefix <- file.path(dir_output_perref_trees, "all_locus")
            fn_locus_perref_treefile <- paste0(fn_locus_perref_prefix, ".treefile")
            
            fn_locus_perref_astral_treefile <- file.path(dir_output_perref_trees, "astral.treefile")
            fn_locus_perref_astral_log <- file.path(dir_output_perref_trees, "astral.log")
            fn_locus_perref_gcf_treefile <- file.path(dir_output_perref_trees, "gcf.cf.tree")
            fn_locus_perref_scf_treefile <- file.path(dir_output_perref_trees, "scf.cf.tree")
            if (all(file.exists(fn_locus_perref_astral_treefile, fn_locus_perref_gcf_treefile, fn_locus_perref_scf_treefile)) && !params$redo) {
                next
            }

            # create doSNOW cluster
            nwcl <- makeCluster(params$thread)
            doSNOW::registerDoSNOW(nwcl)

            # iterate over all locus
            foreach(locus = ls_locus_condition) %dopar% {
                # extract alignment
                fn_input <- file.path(params$dir_genes_alignment, locus, paste0(locus, ".fa"))
                fn_output <- file.path(dir_output_perref_fasta, paste0(locus, ".fa"))
                if (file.exists(fn_output)) {
                    return(NULL)
                }

                # extract headers
                ls_header <- c(ls_refseq, paste0(read,"--",ref))

                f_extract_fasta(fn_input, ls_header, fn_output)
            }

            stopCluster(nwcl)

            # run IQ-TREE2
            f_multiple_tree(dir_output_perref_fasta, fn_locus_perref_prefix, params$thread, params$redo, params$exe_iqtree2)
            alltre_temp <- ape::read.tree(fn_locus_perref_treefile)
            alltre_temp <- alltre_temp[[1]]

            # run ASTRAL
            if (params$is_astral_constrained && file.exists(params$file_species_treefile)) {
                fn_sptree <- file.path(dir_output_perref_trees, "sptree.treefile")
                
                # open species tree
                sptree <- ape::read.tree(params$file_species_treefile)
                sptree <- ape::drop.tip(sptree, tip=sptree$tip.label[!sptree$tip.label%in%alltre_temp$tip.label])
                ape::write.tree(sptree, file=fn_sptree)

                f_astral_constrained(fn_locus_perref_treefile, fn_locus_perref_astral_treefile, fn_locus_perref_astral_log, fn_sptree, params$exe_astral)

            } else {
                f_astral(fn_locus_perref_treefile, fn_locus_perref_astral_treefile, fn_locus_perref_astral_log, params$exe_astral)
            }

            # calculate sCF and gCF
            f_calculate_cf(fn_locus_perref_treefile, fn_locus_perref_astral_treefile, dir_output_perref_fasta, dir_output_perref_trees, params$thread, params$exe_iqtree2)
        }

        log4r::info(fn_logger, paste0("Finished running per-reference tree topology test on ", condition, " trees for ", read, "."))
    }
}
```