---
title: "BUSCO Extraction from Genome Alignment"
---

```{r busco-setup, include=FALSE}
write.table(c("",
              "####################################",
              "####           BUSCO            ####",
              "####################################"),
            file=fn_log, quote=F, row.names=F, col.names=F, append=T)

# create busco directory
dir_busco <- paste0(getwd(), "/busco/")
if (!dir.exists(dir_busco)) {
  dir.create(dir_busco, recursive = T)
}

# readmap directory
dir_readmap <- paste0(getwd(), "/readmap/")
```

```{r busco}
ls_ids <- list.dirs(dir_readmap, recursive=F, full.names=F)

for (i in ls_ids) {
    # extract FASTA filenames
    dir_readmap_id <- paste0(dir_readmap, i, "/")
    file_fasta <- list.files(dir_readmap_id, pattern='*_concat.[1-2].fa', recursive=F, full.names=F)

    # iterate over FASTA files
    for (j in file_fasta) {
        # extract prefix for output directory
        ls_name <- strsplit(j, split="\\_concat|\\.")[[1]]
        prefix <- paste(ls_name[1], ls_name[length(ls_name)-1], sep=".")

        # create outdir
        dir_busco_id <- paste0(dir_busco, prefix, "/")
        if (!dir.exists(dir_busco_id)) {
            dir.create(dir_busco_id, recursive=T)
        }

        # run BUSCO pipeline
        f_run_busco(paste0(dir_readmap_id, j), params$lineage, dir_busco_id, params$mode, params$thread, params$exe_busco)
        log4r::info(fn_logger, paste0("File created: BUSCO analysis for ", prefix, "."))
    }
}
```